name: Java CI/CD Pipeline

trigger:
 batch: true
 branches:
  include:
  - main
  - develop

pool:
  vmaImage: ubuntu-latest

variables:
  JAVA_SDK_VERSION: 17

stages:
- stage: Compile_code
  jobs:
  - job: compile_code
    steps:
    - script: |
        echo "checking Maven Installation"
        mvn -v || {
          echo "Maven not found. Installing maven"
          sudo apt-get update
          sudeo apt-get install -y maven
        }
      displayName: Instaslling maven
    
    - script: |
        echo "Java Version:"
        java -version
      displayName: checking java version
    
    - script: |
         echo "Java code compilation"
         mvn clean compile
      displayName: code compilation

     

  
   
    
     

